### ISSUE TITLE
fatality win dll

### ISSUE THREAD

**Issue by Furious907** [rfoxxxyshit/aye-ahk-loader#10]
В прошлых версиях данного инжектора была возможность внедрить в игру чит под названием fatality.win. Не могли бы вы скинуть dll данного чита, а может и всех остальных на главной странице проекта.

**Comment by ghost** [comment]
@Furious907 К сожалению, у меня нету dll fatality.win, обновленной под новую версию игры, как и остальных читов которые присутствовали ранее.

**Comment by Furious907** [comment]
спасибо за быстрый ответ!
