### ISSUE TITLE
Что такое Lua Addon?

### ISSUE THREAD

**Issue by Furious907** [rfoxxxyshit/aye-ahk-loader#11]
В данном инжекторе есть множество читов и самый последний это Lua Addon, что это такое? Объясните пожалуйста для новичка в сфере читов.

**Comment by ghost** [comment]
@Furious907 Это addon с lua api для otc

**Comment by Furious907** [comment]
а для чего это нужно?

**Comment by Furious907** [comment]
и что инжектить первым?

**Comment by Furious907** [comment]
@m4x3r1337 ?

**Comment by Ulbwaa** [comment]
@Furious907 маму

**Comment by Furious907** [comment]
@Ulbwaa к чему ты это написал?

**Comment by ghost** [comment]
@Furious907 Это нужно для расширений фукнций чита, за счет lua скриптов. Инжектить первым нужно сам аддон, а потом сам otc

**Comment by Furious907** [comment]
@m4x3r1337 спасибки
