### ISSUE TITLE
Не работает всё в AYE Loader

### ISSUE THREAD

**Issue by ZomComp** [rfoxxxyshit/aye-ahk-loader#12]
![Screenshot_2](https://user-images.githubusercontent.com/68600900/88065784-b7979c00-cb75-11ea-8ca8-52b97f383a0b.png)
![Screenshot_3](https://user-images.githubusercontent.com/68600900/88065788-b8c8c900-cb75-11ea-9d7f-c405fa8a6bc0.png)
![Screenshot_4](https://user-images.githubusercontent.com/68600900/88065792-b9615f80-cb75-11ea-8303-74e9941e7d7c.png)
![Screenshot_5](https://user-images.githubusercontent.com/68600900/88065795-b9615f80-cb75-11ea-8c90-f84dbacd1fe7.png)

**Comment by ghost** [comment]
@ZomComp Может быть проблемы с интернет подключением, попробуй через впн.

**Comment by ZomComp** [comment]
Не работает

**Comment by ghost** [comment]
@ZomComp Попробуй открыть [этот](https://raw.githubusercontent.com/m4x3r1337/otc-direct-link/master/cheats.ini) файл, и если все хорошо, то скорее всего антивирус либо же брандмауэр блокирует доступ к интернету у лоадера.

**Comment by ZomComp** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/68600900/88068331-ba47c080-cb78-11ea-847a-e6f0ba89f209.png)

**Comment by ghost** [comment]
@ZomComp Отключи антивирусы/брандмауэры

**Comment by ZomComp** [comment]
Их нету ; Отключил бранэмаузер ничиго не работает

**Comment by ZomComp** [comment]
Старая версия вашей программы работает (1.3.1)

**Comment by rfoxxxy** [comment]
@ZomComp рограммыы

**Comment by ghost** [comment]
@ZomComp Тогда советую вам пользоваться именно ей, пока мы не разберемся в проблеме.

**Comment by ZomComp** [comment]
Но там 
![Screenshot_8](https://user-images.githubusercontent.com/68600900/88068779-55d93100-cb79-11ea-85f7-cc35d3857729.png)

**Comment by ZomComp** [comment]
Также но зато инжектит Load DLL

**Comment by ZomComp** [comment]
Я сделал очистку компьютера через CCleaner и перестал работать AYE Loader

**Comment by ghost** [comment]
@ZomComp Возможно что вся проблема описана на [этом](https://user-images.githubusercontent.com/68600900/88065784-b7979c00-cb75-11ea-8ca8-52b97f383a0b.png) скриншоте, который вы приложили ранее. Попробуйте провести проверку системы введя в командную строку от имени администратора `sfc /scannow` и установить все обновления ОС.

**Comment by ZomComp** [comment]
Все обновление установлены ; sfc /scannow зделал ; осталася такая же проблемма

**Comment by rfoxxxy** [comment]
@ZomComp Поможет только переустановка системы, увы.

**Comment by ZomComp** [comment]
Я же говорю ; проблемма может в этом - 

> Я сделал очистку компьютера через CCleaner и перестал работать AYE Loader

**Comment by ghost** [comment]
@ZomComp Попробуйте переустановить ОС, скорее всего CCleaner затронул системные файлы, из-за которого лоадер не может загрузить список читов из сети.

**Comment by Ulbwaa** [comment]
@m4x3r1337 16 лет💁 я обожаю хайп💗🔥🔥 хайп это моя жизнь😍шмот - вэнсы олд скул👟кепка глориа джинс🎩худи трашер👕🔥музыка элджей лизер буерак пошлая моли 👍💜

**Comment by Ulbwaa** [comment]
@Ulbwaa
