### ISSUE TITLE
Апдейт

### ISSUE THREAD

**Issue by Furious907** [rfoxxxyshit/aye-ahk-loader#17]
А шо добавили?

**Comment by ghost** [comment]
@Furious907 
![image](https://user-images.githubusercontent.com/22843270/89107321-47282f00-d441-11ea-83eb-e8cf2ae88a2a.png)

**Comment by Furious907** [comment]
я дэбик можно по русски

**Comment by ghost** [comment]
> я дэбик можно по русски

![image](https://user-images.githubusercontent.com/22843270/89107352-8f475180-d441-11ea-9466-98a6a92ceb7f.png)

**Comment by Furious907** [comment]
> > я дэбик можно по русски
> 
> ![image](https://user-images.githubusercontent.com/22843270/89107352-8f475180-d441-11ea-9466-98a6a92ceb7f.png)

так это по английски

**Comment by ghost** [comment]
> > > я дэбик можно по русски
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22843270/89107352-8f475180-d441-11ea-9466-98a6a92ceb7f.png)
> 
> так это по английски

![image](https://user-images.githubusercontent.com/22843270/89107394-e5b49000-d441-11ea-8dc6-947a36223efc.png)
вот по русски

**Comment by rfoxxxy** [comment]
> > > я дэбик можно по русски
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22843270/89107352-8f475180-d441-11ea-9466-98a6a92ceb7f.png)
> 
> так это по английски

Чейнжлог берется с гитхаба и не может быть переведен.
Кратко - лоадер теперь будет показывать чейжлог, если найдет обновление

**Comment by Furious907** [comment]
аллилуя спасибо
