### ISSUE TITLE
Не инжектится

### ISSUE THREAD

**Issue by kosenko544** [rfoxxxyshit/aye-ahk-loader#18]
С такой ошибкой.
https://imgur.com/a/NZts2P2

**Comment by ghost** [comment]
@kosenko544 External Module Bypasser - не наша разработка. Мы ее используем для байпасса "нового античита" valve. Видимо, в её работе произошел сбой. Вы можете сообщить о нем разработчику: 0x000cb

**Comment by kosenko544** [comment]
0x000cb умер вродь не?
Проблему решил переустановкой винды(обновлялся с 1909 до 2004 появились проблемы с контекст меню, установил чистую 2004 все ворк)
