### ISSUE TITLE
Error Couldn't find function 'LoadLibrary' in kernel32.dll when injecting

### ISSUE THREAD

**Issue by ghost** [rfoxxxyshit/aye-ahk-loader#2]
# блять я не знаю как фиксить автору 0 лет помогите!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by m4x3r1337** [comment]
@m4x3r1337 @rf0x1d

**Comment by rfoxxxy** [comment]
@m4x3r1337 фикса не будет кому не похуй

**Comment by m4x3r1337** [comment]
@rfoxxxy

**Comment by Ulbwaa** [comment]
@m4x3r1337 сосеш

**Comment by m4x3r1337** [comment]
@Ulbwaa сам сосеш

**Comment by ghost** [comment]
блять я ахк не так поставил ладно

**Comment by s1linw** [comment]
я красивая

**Comment by rfoxxxy** [comment]
@s1linw Ладно

**Comment by s1linw** [comment]
### **спасибо**

**Comment by mqx666** [comment]
у меня писюн огромный сосать будете?

**Comment by m4x3r1337** [comment]
@mqx666 Да

**Comment by rickismaru** [comment]
КОПРО 🍫 
ПИСИНГ ☔ 
СКВИРТ 💦 
ФИСТИНГ 🍆 
МЕСЯЧНЫЕ 💧 
А так же онлайн трансляции, страппон, унижение раба, реал встречи (Москва) 😱 
Все это ждет тебя здесь 👇 
@yid54(https://vk.com/yid54)
