### ISSUE TITLE
Отключение автообновления дллок

### ISSUE THREAD

**Issue by rfoxxxy** [rfoxxxyshit/aye-ahk-loader#3]
Хочеца...

**Comment by ghost** [comment]
не хочеца...

**Comment by ilyha-torpeda** [comment]
я сосал

**Comment by m4x3r1337** [comment]
@rickismaru нахуй ты что-то сюда пишешь, позер?

**Comment by rickismaru** [comment]
да ты лошок ебаный помолчи

**Comment by m4x3r1337** [comment]
@rickismaru zxc выскачиш?

**Comment by m4x3r1337** [comment]
@m4x3r1337 уебище

**Comment by rickismaru** [comment]
хахах да ты и пяти минут не простоишь в миду против мя
