### ISSUE TITLE
Error code: 126

### ISSUE THREAD

**Issue by xsslize** [rfoxxxyshit/aye-ahk-loader#5]
Couldn't find function "LoadLibrary" in kernel32.dll

**Comment by rfoxxxy** [comment]
Install AHK ANSI 32 bit.

**Comment by ghost** [comment]
> Couldn't find function "LoadLibrary" in kernel32.dll

@pax20die Did you compile from the source, or did you using the release already compiled?

**Comment by rfoxxxy** [comment]
Not relevant. Closed.
